blueprints/profile/__init__.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import logout_user, current_user
from app import db, request
from models import User

class ProfilePage:

	def __init__(self, flask_app, bcrypt):
		profile_bp = Blueprint("profile", __name__, template_folder="templates", static_folder="static", static_url_path="/profile/static/")

		@profile_bp.route('/profile')
		def profile():
			if current_user.is_authenticated:
				review_data = current_user.get_reviews()
				return render_template("profile.html", user=current_user, username=str(current_user.username), full_name=str(current_user.full_name), address=str(current_user.full_name), email=str(current_user.email), review_data=review_data)
			else:
				return redirect(url_for("login.login"))

		@profile_bp.route('/profile/edit', methods=["GET", "POST"])
		def edit():
			if current_user.is_authenticated:
				if request.method == "POST":
					full_name = request.form.get("full_name")
					email = request.form.get("email")
					address = request.form.get("address")
					print(full_name, email, address)
					if full_name != "" and email != "" and address != "":
						current_user.update(full_name, email, address)
						return redirect(url_for("profile.profile"))
					else:
						return render_template("edit_profile.html", user=current_user, full_name=str(full_name), email=str(email), address=str(address))
				else:
					return render_template("edit_profile.html", user=current_user, full_name=str(current_user.full_name), email=str(current_user.email), address=str(current_user.address))
			else:
				return redirect(url_for("login.login"))

		@profile_bp.route('/profile/logout')
		def logout():
			logout_user()
			return redirect(url_for("login.login"))
		
		@profile_bp.route('/profile/delete')
		def delete():
			user_to_delete = User.query.filter(User.id == current_user.id).first()
			logout_user()
			user_to_delete.delete()
			return redirect(url_for("main_page.main_page"))


		flask_app.register_blueprint(profile_bp)

blueprints/profile/templates/edit_profile.html
{% extends 'navbar_template.html' %}

{% block head %}
<title>Edit Profile</title>
{% endblock %}


{% block content %}
<form action="{{ url_for('profile.edit') }}" method="POST">
	<div class="container border mt-4 p-4">
		<h1>Edit Profile</h1>
		<hr>
		<div class="mb-3">
			<label class="form-label">Full Name</label>
			<input type="text" name="full_name" class="form-control" required="required"
				{% if full_name is defined and full_name %}
					value={{full_name}}
				{% endif %}
			>
		</div>
		<div class="mb-3">
			<label class="form-label">Email address</label>
			<input type="email" name="email" class="form-control" required="required"
				{% if email is defined and email %}
					value={{email}}
				{% endif %}
			>
		</div>
		<!-- <div class="mb-3">
			<label class="form-label">Password</label>
			<input type="password" name="password" class="form-control" required="required" minlength="8"
				{% if password is defined and password %}
					value={{password}}
				{% endif %}
			>
			<p class="text-muted fw-lighter">Must be at least 8 characters long.</p>
		</div> -->
		<div class="mb-3">
			<label class="form-label">Address</label>
			<input type="text" name="address" class="form-control" required="required"
				{% if address is defined and address %}
					value={{address}}
				{% endif %}
			>
		</div>
		<div class="mb-3">
			<button type="submit" class="btn btn-primary">Save Edit</button>
		</div>
	</div>
</form>
{% endblock %}

blueprints/profile/templates/profile.html
{% extends 'navbar_template.html' %}

{% block head %}
<title>Profile</title>
<link rel="stylesheet" href="{{ url_for('profile.static', filename='profile.css') }}">
{% endblock %}


{% block content %}
<div class="page-container">
	<div class="main-block">
		<div class="container mt-4 p-4">
			<h1>Profile</h1>
			<hr>
			
			<h2> {{ username }} </h1>
			<div>
				
				<p>
					<b>Full Name</b> : {{ full_name }}
				</p>

				<p>
					<b>Email</b> : {{ email }}
				</p>

				<p>
					<b>Email</b> : {{ address }}
				</p>

				

			</div>

			<br>
			<br><br>
			
			<div class="button-container">
				<div class="left-buttons">
					<a href="{{ url_for('profile.edit') }}" class="text-reset text-decoration-none">
						<button type="button" class="btn btn-primary">
							Edit
						</button>
					</a>
				</div>
				
				<div class="right-buttons">
					<button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#logout_modal" id="logout_modal_button">
						Logout
					</button>

					<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete_modal" id="delete_modal_button">
						Delete Account
					</button>
				</div>
			</div>
		
			

			<!-- Logout Modal -->
			<div class="modal fade" id="logout_modal" tabindex="-1" aria-labelledby="logout_modal_label" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<h1 class="modal-title fs-5" id="logout_modal_label">Modal title</h1>
							<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
						</div>
						<div class="modal-body">
							Are you sure you want to logout?
						</div>
						<div class="modal-footer">
							<a href="{{ url_for('profile.logout') }}" class="text-reset text-decoration-none">
								<button type="button" class="btn btn-danger">Logout</button>
							</a>
							<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
						</div>
					</div>
				</div>
			</div>

			<!-- Delete Modal -->
			<div class="modal fade" id="delete_modal" tabindex="-1" aria-labelledby="delete_modal_label" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<h1 class="modal-title fs-5" id="delete_modal_label">Modal title</h1>
							<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
						</div>
						<div class="modal-body">
							Are you sure you want to delete this account? This action cannot be undone.
						</div>
						<div class="modal-footer">
							<a href="{{ url_for('profile.delete') }}" class="text-reset text-decoration-none">
								<button type="button" class="btn btn-danger">Delete</button>
							</a>
							<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


	<div class="side-Block">
		<div class="container mt-4 p-4">
			<h1>Previous Purchases</h2>
				<hr>
				{% for data in review_data %}
				<div class="Transaction_List">
					<div class="transaction-item">
						<a href="{{url_for('keyboard.keyboard_details', keyboard_id=data.data.1.id)}}" class="text-reset text-decoration-none">
							<img src="{{ url_for('static', filename=data.data.1.image_url) }}" alt="">
						</a>
						<a href="{{url_for('keyboard.keyboard_details', keyboard_id=data.data.1.id)}}" class="text-reset text-decoration-none">
							<div class="item-details">
								<h5>{{ data.data.1.name }}</h5>
								<h6><b>Color:</b> {{ data.data.2.name }} | <b>Switch Type:</b> {{ data.data.3.name }}</h6>
								{% if data.stars != "" %} <h6>{{ data.stars }} </h6> {% endif %}
								{% if data.data.0.description == "None" %} <p>{{ data.data.0.description }} </p> {% endif %}
							</div>
						</a>
						
						<div class="ce">
							{% if data.data.0.rating == -1 %}
								<a href="{{url_for('review.review', review_id=data.data.0.id)}}" class="text-reset text-decoration-none">
									<button type="button" class="btn btn-sm btn-dark">
										Review
									</button>
								</a>
							{% endif %}
							<br>
							<br>
						</div>
						
						
				
					</div>

				</div>
				{% endfor %}
		</div>
	</div>
</div>
{% endblock %}