blueprints/products/__init__.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from flask_login import current_user
from app import db, request

class ProductsPage:
	products_bp = Blueprint("products", __name__, template_folder="templates", static_folder="static", static_url_path="/showcase/static/")
	
	def __init__(self, flask_app, bcrypt):		
		from models import Keyboard, Color, Switch

		@self.products_bp.route('/keyboards')
		def keyboards():
			is_ascending = request.args.get("asc", "true") == "true"
			return render_template("keyboards.html", keyboard_data=Keyboard.get_data_all(is_ascending))
		
		@self.products_bp.route('/keyboards/get_variants', methods=['POST'])
		def get_variants():
			if current_user.is_authenticated:
				data = request.get_json()
				keyboard_id = int(data["keyboard_id"])
				keyboard = Keyboard.get_by_id(keyboard_id)
				colors = [color.to_dict() for color in keyboard.get_variants(Color)]
				switches = [switch.to_dict() for switch in keyboard.get_variants(Switch)]
				return jsonify({'success' : True, 'colors': colors, 'switches' : switches})
			else:
				return jsonify({'success' : False})

		@self.products_bp.route('/keyboards/add_to_cart', methods=['POST'])
		def add_to_cart():
			data = request.get_json()
			keyboard_id = int(data["keyboard_id"])
			keyboard = Keyboard.get_by_id(keyboard_id)
			color_id = int(data["variant_info"]["color"])
			switch_id = int(data["variant_info"]["switch"])
			current_user.add_to_cart(keyboard, color_id, switch_id, 1)
			return jsonify({'keyboard_name': keyboard.name})
				
		@self.products_bp.route('/accessories')
		def accessories():
			return render_template("keyboards.html")

		flask_app.register_blueprint(self.products_bp)

blueprints/products/templates/keyboards.html
{% extends 'navbar_template.html' %}

{% block head %}
<title>Keyboards</title>
<link rel="stylesheet" href="{{ url_for('products.static', filename='keyboards.css') }}">
{% endblock %}

{% block content %}

<div id="alert" class="alert alert-success alert-dismissible fade d-none mt-3" role="alert">
	<strong id="product-name"></strong> was added to your cart.
</div>

<div class="page_container">
	<div class="price-selector-container">
		<select id="price-selector" class="form-select w-auto" data-base-url="{{ url_for('products.keyboards') }}">
			<option>-- Sort by Price --</option>
			<option value="true">Ascending</option>
			<option value="false">Descending</option>
		</select>

	</div>

	<div class="main-block">
   		<div class="row">
				{% for data in keyboard_data %}
				<div class="product-container" id="container-{{ data.keyboard.id }}">
					<div class="product-img-container">
						<img src="{{ url_for('static', filename='assets/xera87.jpg') }}" alt="">
					</div>
					<div class="product_text_container">
						<a href="{{ url_for('keyboard.keyboard_details', keyboard_id=data.keyboard.id) }}" class="text-reset text-decoration-none">
						<h3> {{ data.keyboard.name }} </h3>
						<p> {{ data.keyboard.subtitle }} </p>
						<div class="rating">
							{% if data.stars != "" %}
								<span class="stars">{{ data.stars }}</span>
							{% endif %}
							<span class="ratings">{{ data.number_of_reviews }} Ratings</span>
						</div>
						<div class="price">
							<span class="current-price">Rp. {{ data.discounted_price }} {% if data.keyboard.discount > 0 %} (-{{ data.keyboard.discount }} %) {% endif %} </span>
						</div>
						{% if data.keyboard.discount > 0 %}
							<div class="price">
								<span class="original-price">Rp. {{ data.price }} </span>
							</div>
						{% endif %}
						</a>
						<button class="add-to-cart open-modal" id="cart-btn-{{ data.keyboard.id }}" data-id="{{ data.keyboard.id }}"
							data-bs-toggle="modal" data-bs-target="#cart_modal" id="cart_modal_button">
							Add to Cart
						</button>
					</div>
				</div>
				{% endfor %}
    	</div>
	</div>
</div>

<!-- Variant Modal -->
<div class="modal fade" id="cart_modal" tabindex="-1" aria-labelledby="cart_modal_label" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5" id="cart_modal_label">Select Variant</h1>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div class="product-options">
					<label>Warna:</label>
					<div class="color-options btn-group-toggle" data-toggle="buttons" id="color-options">
					</div>
					<label>Switch:</label>
					<div class="switch-options btn-group-toggle" id="switch-options">
					</div>
				</div>
			</div>
			
			<div class="modal-footer">
				<button type="button" class="add-to-cart" id="finalize" data-bs-dismiss="modal">Add to Cart</button>
			</div>
		</div>
	</div>
</div>

<script src="{{ url_for('products.static', filename='keyboards.js') }}"></script>

{% endblock %}