blueprints/login/__init__.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user
from app import request
from models import User

class LoginPage:
	

	def __init__(self, flask_app, bcrypt):
		login_bp = Blueprint("login", __name__, template_folder="templates", static_folder="static", static_url_path="/login/static/")
		
		@login_bp.route('/login', methods=["GET", "POST"])
		def login():
			message = ""
			if request.method == "POST":
				identifier = request.form.get("identifier")
				password = request.form.get("password")
				if self.validate_login(identifier, password, bcrypt):
					return redirect(url_for("main_page.main_page"))
				else:
					message = "Invalid username or password."		
			return render_template('login.html', message=message)
		

		flask_app.register_blueprint(login_bp)

	def validate_login(self, identifier, password, bcrypt):
		user = (User.get_by_email(identifier) if "@" in identifier else User.get_by_username(identifier))
		if user is not None:
			if bcrypt.check_password_hash(user.password, password):
				login_user(user)
				return True
		return False

blueprints/login/templates/login.html
{% extends 'navbar_template.html' %}

{% block head %}
<title>Login</title>
<link rel="stylesheet" href="{{ url_for('login.static', filename='login.css') }}">

{% endblock %}


{% block content %}
<div class="background">
	<div class="middle-box">
		<form action="{{ url_for('login.login') }}" method="POST">
			{% if message is defined and message %}
				<div class="alert alert-warning">  <strong>  {{ message }} </strong></div>
			{% endif %}
			<div class="container border mt-4 p-4">
				<h1>Login</h1>
				<hr>
				<div class="mb-3">
					<label for="exampleInputUsername1" class="form-label">Email or Username</label>
					<input type="text" class="form-control" name="identifier" required="required">
				</div>
				<div class="mb-3">
					<label for="exampleInputPassword1" class="form-label">Password</label>
					<input type="password" class="form-control" name="password" required="required">
				</div>
				<div class="mb-3">
					<button type="submit" class="btn btn-success">Login</button>
				</div>
				<p>Don't have an account? <a href="{{ url_for('register.register') }}">Sign Up</a>.</p>
			</div>
		</form>
	</div>
</div>
{% endblock %}